name = "butaneprotocol/btn-deployment"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'butaneprotocol/btn-deployment'"

[repository]
user = "butaneprotocol"
project = "btn-deployment"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
